# Generated by Django 5.0 on 2023-12-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_results_created_at_results_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='question_type',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='question_type',
            field=models.CharField(choices=[('select_one', 'Выбор ответа'), ('short_reply', 'Краткий ответ')], default='select_one', max_length=64, verbose_name='Тип вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='results',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-04-12 10:10', verbose_name='Дата решения'),
            preserve_default=False,
        ),
    ]
