# Generated by Django 5.0 on 2023-12-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_assignment_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='question_type',
        ),
        migrations.AddField(
            model_name='assignment',
            name='question_type',
            field=models.CharField(choices=[('select_one', 'Выбор ответа'), ('short_reply', 'Краткий ответ')], default='select_one', max_length=64, verbose_name='Тип вопроса'),
            preserve_default=False,
        ),
    ]
